import React, { useState, useEffect } from 'react';
import { useOutletContext, Link } from 'react-router-dom';
import { alertService } from '../../services/alertService';
import RiskBadge from '../../components/common/RiskBadge';
import { 
  Bell, 
  Smartphone, 
  AlertOctagon, 
  AlertTriangle, 
  CheckCheck, 
  Clock, 
  Search, 
  Filter, 
  CheckCircle2, 
  ExternalLink,
  MessageSquare,
  Sparkles,
  Calendar,
  BookOpen,
  User,
  Inbox
} from 'lucide-react';

export default function AlertsPage() {
  const { openSmsModal } = useOutletContext() || {};
  const [activeTab, setActiveTab] = useState('alerts'); // 'alerts' | 'sms'
  const [alerts, setAlerts] = useState([]);
  const [smsLogs, setSmsLogs] = useState([]);
  const [searchTerm, setSearchTerm] = useState('');
  const [filterType, setFilterType] = useState('All'); // 'All' | 'Attendance' | 'CA' | 'Critical' | 'Read' | 'Unread'

  useEffect(() => {
    loadData();
    const handleUpdate = () => loadData();
    window.addEventListener('sams_data_updated', handleUpdate);
    return () => window.removeEventListener('sams_data_updated', handleUpdate);
  }, []);

  const loadData = () => {
    setAlerts(alertService.getAllAlerts());
    setSmsLogs(alertService.getAllSmsLogs());
  };

  const handleMarkAsRead = (id) => {
    alertService.markAsRead(id);
    loadData();
  };

  const handleMarkAllRead = () => {
    alertService.markAllAsRead();
    loadData();
  };

  // Filter alerts based on requested criteria
  const filteredAlerts = alerts.filter(al => {
    const term = searchTerm.toLowerCase();
    const matchesSearch = 
      al.studentName?.toLowerCase().includes(term) ||
      (al.matricNo || al.matricNumber || '').toLowerCase().includes(term) ||
      al.courseCode?.toLowerCase().includes(term) ||
      al.message?.toLowerCase().includes(term);

    if (!matchesSearch) return false;

    switch (filterType) {
      case 'Attendance':
        return al.type?.toLowerCase().includes('attendance') || al.message?.toLowerCase().includes('attendance');
      case 'CA':
        return al.type?.toLowerCase().includes('ca') || al.message?.toLowerCase().includes('ca');
      case 'Critical':
        return al.severity === 'critical' || al.type?.toLowerCase().includes('critical');
      case 'Read':
        return al.status === 'read';
      case 'Unread':
        return al.status === 'unread';
      case 'All':
      default:
        return true;
    }
  });

  const filteredSms = smsLogs.filter(s =>
    (s.recipientName || s.recipient || '').toLowerCase().includes(searchTerm.toLowerCase()) ||
    (s.recipientPhone || s.phone || '').includes(searchTerm) ||
    s.message?.toLowerCase().includes(searchTerm.toLowerCase())
  );

  const filterTabs = [
    { key: 'All', label: 'All Alerts', count: alerts.length },
    { key: 'Attendance', label: 'Attendance Risk', count: alerts.filter(a => a.type?.toLowerCase().includes('attendance') || a.message?.toLowerCase().includes('attendance')).length },
    { key: 'CA', label: 'CA Risk', count: alerts.filter(a => a.type?.toLowerCase().includes('ca') || a.message?.toLowerCase().includes('ca')).length },
    { key: 'Critical', label: 'Critical Risk', count: alerts.filter(a => a.severity === 'critical' || a.type?.toLowerCase().includes('critical')).length },
    { key: 'Unread', label: 'Unread', count: alerts.filter(a => a.status === 'unread').length },
    { key: 'Read', label: 'Read', count: alerts.filter(a => a.status === 'read').length },
  ];

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
        <div>
          <h1 className="text-xl font-display font-bold text-slate-900">Academic Alert Centre & SMS Dispatch Hub</h1>
          <p className="text-xs text-slate-500 mt-0.5">
            Automated early-warning notifications generated by the SAMS Risk Engine for Attendance &lt;60% and CA &lt;40%.
          </p>
        </div>

        <div className="flex items-center gap-2">
          {activeTab === 'alerts' && alerts.some(a => a.status === 'unread') && (
            <button
              onClick={handleMarkAllRead}
              className="px-3 py-1.5 bg-slate-100 hover:bg-slate-200 text-slate-700 rounded-xl text-xs font-semibold transition cursor-pointer"
            >
              Mark All as Read
            </button>
          )}
          <button
            onClick={openSmsModal}
            className="flex items-center gap-1.5 px-3.5 py-1.5 bg-fud-900 hover:bg-fud-800 text-white rounded-xl text-xs font-semibold shadow-sm transition cursor-pointer"
          >
            <Smartphone size={14} />
            <span>Open SMS Simulator</span>
          </button>
        </div>
      </div>

      {/* Main View Tabs (Alerts Feed vs SMS Dispatch Log) */}
      <div className="flex items-center gap-2 border-b border-slate-200">
        <button
          onClick={() => setActiveTab('alerts')}
          className={`flex items-center gap-2 px-4 py-2.5 rounded-t-xl text-xs font-semibold transition border-b-2 cursor-pointer ${
            activeTab === 'alerts'
              ? 'border-fud-900 bg-white text-fud-900 shadow-2xs font-bold'
              : 'border-transparent text-slate-500 hover:text-slate-900 hover:bg-slate-100/60'
          }`}
        >
          <Bell size={14} />
          <span>Academic Alerts ({alerts.length})</span>
          {alerts.filter(a => a.status === 'unread').length > 0 && (
            <span className="bg-rose-500 text-white text-[9px] font-bold px-1.5 py-0.2 rounded-full">
              {alerts.filter(a => a.status === 'unread').length} New
            </span>
          )}
        </button>

        <button
          onClick={() => setActiveTab('sms')}
          className={`flex items-center gap-2 px-4 py-2.5 rounded-t-xl text-xs font-semibold transition border-b-2 cursor-pointer ${
            activeTab === 'sms'
              ? 'border-fud-900 bg-white text-fud-900 shadow-2xs font-bold'
              : 'border-transparent text-slate-500 hover:text-slate-900 hover:bg-slate-100/60'
          }`}
        >
          <Smartphone size={14} />
          <span>Simulated SMS Log ({smsLogs.length})</span>
          <span className="bg-emerald-100 text-emerald-700 text-[10px] font-bold px-1.5 py-0.2 rounded">
            Simulated
          </span>
        </button>
      </div>

      {/* Filter Tabs for Alerts */}
      {activeTab === 'alerts' && (
        <div className="flex items-center gap-1.5 overflow-x-auto pb-1">
          {filterTabs.map((tab) => (
            <button
              key={tab.key}
              onClick={() => setFilterType(tab.key)}
              className={`px-3 py-1.5 rounded-xl text-xs font-semibold transition cursor-pointer flex items-center gap-1.5 whitespace-nowrap ${
                filterType === tab.key
                  ? 'bg-fud-900 text-white shadow-sm'
                  : 'bg-white text-slate-600 hover:bg-slate-100 border border-slate-200'
              }`}
            >
              <span>{tab.label}</span>
              <span className={`text-[10px] px-1.5 py-0.2 rounded-full ${
                filterType === tab.key ? 'bg-white/20 text-white' : 'bg-slate-100 text-slate-600'
              }`}>
                {tab.count}
              </span>
            </button>
          ))}
        </div>
      )}

      {/* Search Bar */}
      <div className="bg-white p-4 rounded-2xl border border-slate-200 shadow-subtle">
        <div className="relative">
          <Search size={15} className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-400" />
          <input
            type="text"
            placeholder={activeTab === 'alerts' ? "Search alerts by student name, matriculation number, course, or message..." : "Search simulated SMS messages..."}
            value={searchTerm}
            onChange={(e) => setSearchTerm(e.target.value)}
            className="w-full pl-9 pr-4 py-2 text-xs border border-slate-200 rounded-xl focus:outline-none focus:ring-2 focus:ring-fud-500 bg-white"
          />
        </div>
      </div>

      {/* Feed Content */}
      {activeTab === 'alerts' ? (
        <div className="space-y-3">
          {filteredAlerts.length === 0 ? (
            <div className="bg-white p-12 rounded-2xl border border-slate-200 text-center text-slate-400 text-xs flex flex-col items-center justify-center space-y-2">
              <Inbox size={32} className="text-slate-300" />
              <p className="font-semibold text-slate-700">No alert records match the selected filter ({filterType}).</p>
              <p className="text-[11px] text-slate-400">Try selecting another filter or searching a different student/course.</p>
            </div>
          ) : (
            filteredAlerts.map((al) => {
              const isCritical = al.severity === 'critical' || al.type?.includes('Critical');
              const matric = al.matricNo || al.matricNumber || 'FCP/CSC/22/001';

              return (
                <div
                  key={al.id}
                  className={`bg-white rounded-2xl border shadow-subtle p-5 transition flex flex-col md:flex-row md:items-center justify-between gap-4 ${
                    al.status === 'unread' ? 'ring-1 ring-fud-300 bg-slate-50/40 border-fud-200' : 'border-slate-200'
                  }`}
                >
                  <div className="flex items-start gap-3.5 flex-1 min-w-0">
                    <div className={`p-2.5 rounded-xl shrink-0 mt-0.5 ${
                      isCritical ? 'bg-rose-100 text-rose-600' : 'bg-amber-100 text-amber-600'
                    }`}>
                      {isCritical ? <AlertOctagon size={20} /> : <AlertTriangle size={20} />}
                    </div>

                    <div className="space-y-1.5 min-w-0 flex-1">
                      <div className="flex flex-wrap items-center gap-2">
                        <span className="font-bold text-xs text-slate-900">{al.type}</span>
                        <span className="bg-slate-100 text-slate-700 font-mono text-[10px] font-bold px-2 py-0.5 rounded-md">
                          {al.courseCode}
                        </span>
                        <span className="bg-slate-100 text-slate-600 text-[10px] px-1.5 py-0.5 rounded font-medium">
                          {al.level}L
                        </span>
                        {al.status === 'unread' ? (
                          <span className="bg-rose-100 text-rose-700 text-[10px] font-bold px-2 py-0.5 rounded-full">
                            Unread
                          </span>
                        ) : (
                          <span className="bg-slate-100 text-slate-500 text-[10px] font-medium px-2 py-0.5 rounded-full">
                            Read
                          </span>
                        )}
                        <span className={`text-[10px] font-bold px-2 py-0.5 rounded-full ${
                          isCritical ? 'bg-rose-50 text-rose-700 border border-rose-200' : 'bg-amber-50 text-amber-700 border border-amber-200'
                        }`}>
                          {isCritical ? 'High Priority' : 'Warning'}
                        </span>
                      </div>

                      <p className="text-xs text-slate-800 leading-relaxed font-medium">
                        {al.message}
                      </p>

                      <div className="flex flex-wrap items-center gap-3 text-[11px] text-slate-500 pt-1">
                        <span className="flex items-center gap-1">
                          <User size={12} className="text-slate-400" />
                          <strong className="text-slate-800">{al.studentName}</strong>
                          <span className="font-mono text-fud-700">({matric})</span>
                        </span>
                        <span>•</span>
                        <span>Recipient: {al.recipient}</span>
                        <span>•</span>
                        <span className="flex items-center gap-1">
                          <Clock size={11} className="text-slate-400" />
                          {new Date(al.createdAt).toLocaleString('en-GB', { day: '2-digit', month: 'short', year: 'numeric', hour: '2-digit', minute: '2-digit' })}
                        </span>
                      </div>
                    </div>
                  </div>

                  <div className="flex items-center gap-2 shrink-0 justify-end pt-2 md:pt-0 border-t md:border-t-0 border-slate-100">
                    {al.status === 'unread' && (
                      <button
                        onClick={() => handleMarkAsRead(al.id)}
                        className="px-3 py-1.5 text-slate-600 hover:text-slate-900 text-xs font-semibold bg-slate-100 hover:bg-slate-200 rounded-xl transition cursor-pointer"
                      >
                        Mark Read
                      </button>
                    )}
                    <Link
                      to={`/coordinator/reports?student=${al.studentId}`}
                      className="px-3.5 py-1.5 bg-fud-900 hover:bg-fud-800 text-white rounded-xl text-xs font-semibold transition"
                    >
                      View Dossier
                    </Link>
                  </div>
                </div>
              );
            })
          )}
        </div>
      ) : (
        /* SMS Dispatch Log Registry */
        <div className="bg-white rounded-2xl border border-slate-200 shadow-subtle overflow-hidden">
          <div className="p-4 bg-slate-50 border-b border-slate-200 flex items-center justify-between">
            <div>
              <h2 className="font-bold text-xs text-slate-900 uppercase tracking-wider">
                Simulated FUD SMS Dispatch Gateway Log
              </h2>
              <p className="text-[11px] text-slate-500">Automated mobile alerts dispatched upon academic threshold violations</p>
            </div>
            <span className="bg-emerald-50 text-emerald-700 border border-emerald-200 text-[10px] font-bold px-2 py-0.5 rounded-full flex items-center gap-1">
              <CheckCheck size={11} />
              Simulated Cellular Network
            </span>
          </div>

          <div className="divide-y divide-slate-100">
            {filteredSms.length === 0 ? (
              <div className="p-12 text-center text-slate-400 text-xs">
                No SMS dispatch logs found.
              </div>
            ) : (
              filteredSms.map((sms) => {
                const recName = sms.recipientName || sms.recipient || 'Student';
                const recPhone = sms.recipientPhone || sms.phone || '+2348030000000';
                const dateVal = sms.dispatchedAt || sms.createdAt;

                return (
                  <div key={sms.id} className="p-4 hover:bg-slate-50/70 transition space-y-2 text-xs">
                    <div className="flex items-start justify-between gap-3">
                      <div className="flex items-center gap-2.5">
                        <div className="w-8 h-8 rounded-full bg-sky-50 text-sky-700 font-bold flex items-center justify-center text-xs border border-sky-200">
                          {recName.charAt(0)}
                        </div>
                        <div>
                          <span className="font-bold text-slate-900">{recName}</span>
                          <span className="text-[11px] text-slate-500 ml-2 font-mono bg-slate-100 px-2 py-0.5 rounded">{recPhone}</span>
                        </div>
                      </div>

                      <div className="text-right">
                        <span className="inline-flex items-center gap-1 text-[10px] font-bold text-emerald-700 bg-emerald-50 border border-emerald-200 px-2.5 py-0.5 rounded-full">
                          <CheckCheck size={11} />
                          {sms.status}
                        </span>
                        <div className="text-[10px] text-slate-400 mt-0.5">
                          {new Date(dateVal).toLocaleString('en-GB', { day: '2-digit', month: 'short', year: 'numeric', hour: '2-digit', minute: '2-digit' })}
                        </div>
                      </div>
                    </div>

                    <div className="bg-slate-50 border border-slate-200/80 p-3.5 rounded-xl font-mono text-[11px] text-slate-700 leading-relaxed">
                      {sms.message}
                    </div>

                    <div className="flex items-center justify-between text-[10px] text-slate-400 px-1">
                      <span>Gateway: FUD Department of Computer Science Simulation Network</span>
                      <span>Message ID: #{sms.id}</span>
                    </div>
                  </div>
                );
              })
            )}
          </div>
        </div>
      )}
    </div>
  );
}
